name: LaTeX Document Compile

on:
  push:
    branches:
    - master
    paths:
    - "docs/**"
    - "!docs/**/*.pdf"
    - ".github/workflows/latex.yaml"
    - "!**/.gitignore"
    - "!**/*.md"
  pull_request:
    branches:
    - master
    paths-ignore:
    - "docs/**"
    - "!docs/**/*.pdf"
    - ".github/workflows/latex.yaml"
    - "!**/.gitignore"
    - "!**/*.md"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            cd docs/presentations/2025_JUN_10
            latexmk slides.tex
      - uses: actions/upload-artifact@v4
        with:
          name: 2025_JUN_10.pdf
          path: docs/presentations/2025_JUN_10/slides.pdf
          if-no-files-found: error
